apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: gcr.io/google-samples/gb-frontend:v5
          name: guestbook-ui
          ports:
            - containerPort: 80
          volumeMounts:
          - name: app-secret-vol
            mountPath: "/app/crds"
            readOnly: true            
      volumes:
      - name: app-secret-vol
        secret:
          secretName: aws-crds-k8s